# Generated by Django 2.0 on 2020-01-05 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteuser',
            name='avatar',
            field=models.URLField(default='http://images.hellozheng.cn/15:2020-01-05-10:38:08.jpg', verbose_name='链接'),
        ),
    ]
