# Generated by Django 2.0 on 2020-01-05 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_siteuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteuser',
            name='jifen',
            field=models.IntegerField(default=100, verbose_name='积分'),
        ),
    ]
