# Generated by Django 2.0 on 2020-01-05 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200105_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteuser',
            name='is_verif',
            field=models.BooleanField(default=False, verbose_name='是否验证'),
        ),
    ]
