# Generated by Django 2.0 on 2020-01-05 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_siteuser_is_verif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteuser',
            name='qianming',
            field=models.CharField(default='', max_length=20, verbose_name='签名'),
        ),
    ]
