# Generated by Django 2.0 on 2020-01-05 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20200105_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteuser',
            name='qianming',
            field=models.CharField(default='这位有点懒', max_length=20, verbose_name='签名'),
        ),
    ]
