# Generated by Django 2.0 on 2020-01-10 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20200105_1705'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='siteuser',
            options={'verbose_name': '用户', 'verbose_name_plural': '用户'},
        ),
    ]
