# Generated by Django 2.0 on 2020-01-08 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('category', models.IntegerField(default=0, verbose_name='分类id')),
                ('updateTime', models.DateField(auto_now=True, verbose_name='更新时间')),
                ('createTime', models.DateField(auto_now_add=True, verbose_name='创建时间')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='分类名称')),
                ('categoryId', models.IntegerField(default=0, verbose_name='分类id')),
                ('updateTime', models.DateField(auto_now=True, verbose_name='更新时间')),
                ('createTime', models.DateField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comm_content', models.TextField(default='', verbose_name='评论内容')),
                ('updateTime', models.DateField(auto_now=True, verbose_name='更新时间')),
                ('createTime', models.DateField(auto_now_add=True, verbose_name='创建时间')),
                ('aid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article', to='index.article')),
                ('comm_uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_user_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='fineLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkname', models.CharField(max_length=10, verbose_name='链接名称')),
                ('linkurl', models.CharField(max_length=100, verbose_name='链接url')),
                ('updateTime', models.DateField(auto_now=True, verbose_name='更新时间')),
                ('createTime', models.DateField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
    ]
