# Generated by Django 2.0 on 2020-01-09 12:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='categoryId',
            field=models.IntegerField(default=0, verbose_name='分类下标'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comm_uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_user_id', to=settings.AUTH_USER_MODEL, verbose_name='评论者'),
        ),
    ]
