# Generated by Django 2.0 on 2020-01-10 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20200110_1917'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='category',
            new_name='cate',
        ),
    ]
