# Generated by Django 2.0 on 2020-01-10 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20200110_1922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='cate',
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.IntegerField(default=0, verbose_name='分类id'),
        ),
    ]
