# Generated by Django 2.0 on 2020-01-16 11:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('index', '0006_auto_20200113_2233'),
    ]

    operations = [
        migrations.CreateModel(
            name='notify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.IntegerField(choices=[(1, '已读'), (0, '未读')], default=0, verbose_name='是否已读')),
                ('content', models.CharField(max_length=50, verbose_name='内容')),
                ('updateTime', models.DateField(auto_now=True, verbose_name='更新时间')),
                ('createTime', models.DateField(auto_now_add=True, verbose_name='创建时间')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '评论通知',
                'verbose_name_plural': '评论通知',
            },
        ),
    ]
