# Generated by Django 2.0 on 2020-01-16 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_notify'),
    ]

    operations = [
        migrations.AddField(
            model_name='notify',
            name='aid',
            field=models.IntegerField(default=0, verbose_name='文章id'),
        ),
    ]
