# Generated by Django 2.0 on 2020-03-01 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_auto_20200120_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_show',
            field=models.BooleanField(choices=[(0, '隐藏'), (1, '显示')], default=1, max_length=1),
        ),
    ]
