# Generated by Django 2.0 on 2020-03-01 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0010_article_is_show'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='is_show',
        ),
    ]
